# Generated by Django 4.2.2 on 2024-12-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0002_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='initials',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Initials'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='is_appuser',
            field=models.BooleanField(default=True, verbose_name='IsAppUser'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='organisation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='permission',
            field=models.CharField(default='No', max_length=10, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='username',
            field=models.CharField(max_length=55, unique=True, verbose_name='Username'),
        ),
    ]
