# Generated by Django 4.2.2 on 2024-12-18 06:58

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0003_alter_applicationuser_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chem_Structure',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('structure_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Structure ID')),
                ('structure_code', models.CharField(blank=True, max_length=15, verbose_name='Structure Code')),
                ('structure_name', models.CharField(blank=True, max_length=50, verbose_name='Structure Name')),
                ('smol', django_rdkit.models.fields.MolField(verbose_name='MOL')),
                ('tfp2', django_rdkit.models.fields.BfpField(blank=True, null=True, verbose_name='Topological-Torsion FP')),
                ('ffp2', django_rdkit.models.fields.BfpField(blank=True, null=True, verbose_name='Feature Morgan FP (FCFP)')),
                ('mfp2', django_rdkit.models.fields.BfpField(blank=True, null=True, verbose_name='Morgan FP (ECFP)')),
                ('nfrag', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='nFrag')),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Charge')),
                ('inchikey', models.CharField(blank=True, max_length=50, verbose_name='InChiKey')),
                ('mf', models.CharField(blank=True, max_length=500, verbose_name='MF')),
                ('mw', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, verbose_name='MW')),
                ('natoms', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='nAtoms')),
                ('hba', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='HBond Acc')),
                ('hbd', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='HBond Don')),
                ('logp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='logP')),
                ('tpsa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='tPSA')),
                ('fractioncsp3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Sp3')),
                ('nrotbonds', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='nRotBond')),
                ('nrings', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='nRings')),
                ('narorings', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='nAroRings')),
                ('nhetarorings', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='nHetAroRings')),
                ('nhetaliphrings', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='nHetAliphRings')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('structure_type', models.ForeignKey(blank=True, db_column='structure_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_structuretype', to='apputil.dictionary', verbose_name='Type')),
            ],
            options={
                'db_table': 'chem_structure',
                'ordering': ['structure_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('project_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Project ID')),
                ('project_name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('organisation', models.CharField(blank=True, max_length=150, verbose_name='Organisation')),
                ('source_id', models.CharField(blank=True, max_length=150, verbose_name='Source')),
                ('pub_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Published')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('project_type', models.ForeignKey(blank=True, db_column='project_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_project_type', to='apputil.dictionary', verbose_name='Type')),
                ('pub_status', models.ForeignKey(blank=True, db_column='pub_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_pub_statust', to='apputil.dictionary', verbose_name='Pub Status')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('compound_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Compound ID')),
                ('compound_code', models.CharField(blank=True, max_length=120, verbose_name='Code')),
                ('compound_name', models.CharField(blank=True, max_length=120, verbose_name='Name')),
                ('source_id', models.CharField(blank=True, max_length=150, verbose_name='Source')),
                ('std_status', models.CharField(blank=True, max_length=10, verbose_name='Std Status')),
                ('std_smiles', models.CharField(blank=True, max_length=2048, verbose_name='Std Smiles')),
                ('std_nfrag', models.SmallIntegerField(default=0, verbose_name='Std nFrag')),
                ('std_salt', models.CharField(blank=True, max_length=100, verbose_name='Std Salt')),
                ('std_ion', models.CharField(blank=True, max_length=100, verbose_name='Std Ion')),
                ('std_solvent', models.CharField(blank=True, max_length=100, verbose_name='Std Solvent')),
                ('std_metal', models.CharField(blank=True, max_length=100, verbose_name='Std Metal')),
                ('std_structure_type', models.CharField(blank=True, max_length=400, verbose_name='Std Type')),
                ('pub_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Published')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('compound_type', models.ForeignKey(blank=True, db_column='compound_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_compound_type', to='apputil.dictionary', verbose_name='Type')),
                ('project_id', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_project_id', to='dcoadd.project', verbose_name='Project ID')),
                ('pub_status', models.ForeignKey(blank=True, db_column='pub_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_pub_statust', to='apputil.dictionary', verbose_name='Pub Status')),
                ('structure_id', models.ForeignKey(blank=True, db_column='structure_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_structure_id', to='dcoadd.chem_structure', verbose_name='Structure ID')),
            ],
            options={
                'db_table': 'compound',
                'ordering': ['compound_id'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_name'], name='prj_pn_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='prj_pt_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['source_id'], name='prj_src_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['compound_name'], name='cmp_name_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['compound_code'], name='cmp_code_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['compound_type'], name='cmp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['project_id'], name='cmp_pid_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['source_id'], name='cmp_src_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['structure_id'], name='cmp_str_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['std_status'], name='cmp_sstat_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['std_nfrag'], name='cmp_snfrag_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['std_structure_type'], name='cmp_sstyp_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['std_salt'], name='cmp_ssalt_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['std_metal'], name='cmp_smetal_idx'),
        ),
        migrations.AddIndex(
            model_name='compound',
            index=models.Index(fields=['pub_status'], name='cmp_pst_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=models.Index(fields=['structure_name'], name='cstruct_dname_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=models.Index(fields=['structure_code'], name='cstruct_dcode_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=models.Index(fields=['inchikey'], name='cstruct_inchi_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=models.Index(fields=['mf'], name='cstruct_mf_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=models.Index(fields=['mw'], name='cstruct_mw_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=models.Index(fields=['natoms'], name='cstruct_natoms_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=models.Index(fields=['nfrag'], name='cstruct_nfrag_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=models.Index(fields=['charge'], name='cstruct_charge_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=django.contrib.postgres.indexes.GistIndex(fields=['smol'], name='cstruct_smol_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=django.contrib.postgres.indexes.GistIndex(fields=['ffp2'], name='cstruct_ffp2_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='cstruct_mfp2_idx'),
        ),
        migrations.AddIndex(
            model_name='chem_structure',
            index=django.contrib.postgres.indexes.GistIndex(fields=['tfp2'], name='cstruct_tfp2_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chem_structure',
            trigger=pgtrigger.compiler.Trigger(name='trigfunc_chemstruct_biu', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                                New.mfp2 := morganbv_fp(NEW.sMol);\n                                New.ffp2 := featmorganbv_fp(NEW.sMol);\n                                New.tfp2 := torsionbv_fp(NEW.sMol);\n                                New.inchikey := mol_inchikey(NEW.sMol);\n                                New.mw := mol_amw(NEW.sMol);\n                                New.mf := mol_formula(NEW.sMol);\n                                New.natoms := mol_numheavyatoms(NEW.sMol);\n                                New.logp := mol_logp(NEW.sMol);\n                                New.tpsa := mol_tpsa(NEW.sMol);\n                                New.nrotbonds = mol_numrotatablebonds(NEW.sMol);\n                                New.fractioncsp3 = mol_fractioncsp3(NEW.sMol);\n                                New.hba = mol_hba(NEW.sMol);\n                                New.hbd = mol_hbd(NEW.sMol);\n                                New.nrings = mol_numrings(NEW.sMol);\n                                New.narorings = mol_numaromaticrings(NEW.sMol);\n                                New.nhetarorings = mol_numaromaticheterocycles(NEW.sMol);\n                                New.nhetaliphrings = mol_numaliphaticheterocycles(NEW.sMol);\n                                RETURN NEW;\n                            ', hash='afa5269e0b58db6d5bf2c9d3e6f5cbbeaa8537c5', operation='INSERT OR UPDATE', pgid='pgtrigger_trigfunc_chemstruct_biu_f8a28', table='chem_structure', when='BEFORE')),
        ),
    ]
