# Generated by Django 4.2.2 on 2024-12-18 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apputil', '0003_alter_applicationuser_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcoadd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('source_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Assay ID')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('organisation', models.CharField(blank=True, max_length=150, verbose_name='Organisation')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('source_type', models.ForeignKey(blank=True, db_column='source_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_source_type', to='apputil.dictionary', verbose_name='Type')),
            ],
            options={
                'db_table': 'source',
                'ordering': ['source_id'],
            },
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('assay_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Assay ID')),
                ('assay_code', models.CharField(blank=True, max_length=50, verbose_name='Assay Code')),
                ('assay_name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('organism', models.CharField(blank=True, max_length=50, verbose_name='Organism')),
                ('strain', models.CharField(blank=True, max_length=50, verbose_name='Strain')),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('assay_type', models.ForeignKey(blank=True, db_column='assay_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_assay_type', to='apputil.dictionary', verbose_name='Assay Type')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('result_type', models.ForeignKey(blank=True, db_column='result_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_result_type', to='apputil.dictionary', verbose_name='Result Type')),
            ],
            options={
                'db_table': 'assay',
                'ordering': ['assay_id'],
            },
        ),
        migrations.AlterField(
            model_name='compound',
            name='source_id',
            field=models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_source_id', to='dcoadd.source', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_id',
            field=models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_source_id', to='dcoadd.source', verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_name'], name='src_pn_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_type'], name='src_pt_idx'),
        ),
        migrations.AddIndex(
            model_name='assay',
            index=models.Index(fields=['assay_name'], name='ass_nm_idx'),
        ),
        migrations.AddIndex(
            model_name='assay',
            index=models.Index(fields=['assay_type'], name='ass_ty_idx'),
        ),
        migrations.AddIndex(
            model_name='assay',
            index=models.Index(fields=['assay_code'], name='ass_co_idx'),
        ),
    ]
