# Generated by Django 4.2.2 on 2024-12-18 07:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apputil', '0003_alter_applicationuser_department_and_more'),
        ('dcoadd', '0002_source_assay_alter_compound_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='additive',
            field=models.CharField(blank=True, max_length=50, verbose_name='Additive'),
        ),
        migrations.AddField(
            model_name='assay',
            name='dye',
            field=models.CharField(blank=True, max_length=50, verbose_name='dye'),
        ),
        migrations.AddField(
            model_name='assay',
            name='media',
            field=models.CharField(blank=True, max_length=50, verbose_name='Media'),
        ),
        migrations.CreateModel(
            name='Testplate',
            fields=[
                ('astatus', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Status')),
                ('acreated_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('aupdated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated at')),
                ('adeleted_at', models.DateTimeField(editable=False, null=True, verbose_name='Deleted at')),
                ('testplate_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Project ID')),
                ('source_code', models.CharField(blank=True, max_length=150, verbose_name='Source Code')),
                ('plate_size', models.CharField(blank=True, max_length=25, verbose_name='Plate Size')),
                ('plate_material', models.CharField(blank=True, max_length=25, verbose_name='Plate Material')),
                ('positive_control', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7), size=4)),
                ('negative_control', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7), size=4)),
                ('sample_stats', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7), size=4)),
                ('edge_stats', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7), size=2)),
                ('zfactor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plate_qc', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acreated', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_acreated_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('adeleted', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_adeleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('assay_id', models.ForeignKey(blank=True, db_column='assay_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_assay_id', to='dcoadd.assay', verbose_name='Assay')),
                ('aupdated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_aupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('plate_quality', models.ForeignKey(blank=True, db_column='plate_quality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_plate_quality', to='apputil.dictionary', verbose_name='Plate Quality')),
                ('readout_type', models.ForeignKey(blank=True, db_column='readout_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_readout_type', to='apputil.dictionary', verbose_name='Readout Type')),
                ('source_id', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_source_id', to='dcoadd.source', verbose_name='Source')),
            ],
            options={
                'db_table': 'tesplate',
                'ordering': ['testplate_id'],
                'indexes': [models.Index(fields=['assay_id'], name='tpw_ass_idx'), models.Index(fields=['source_id'], name='tpw_src_idx')],
            },
        ),
    ]
