# Generated by Django 4.2.2 on 2024-12-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcoadd', '0004_remove_assay_result_type_assay_plate_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_doseresponse',
            options={'ordering': ['compound_id']},
        ),
        migrations.AlterModelOptions(
            name='activity_singleconc',
            options={'ordering': ['compound_id']},
        ),
        migrations.AddIndex(
            model_name='activity_doseresponse',
            index=models.Index(fields=['compound_id'], name='adr_cmp_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_doseresponse',
            index=models.Index(fields=['assay_id'], name='adr_ass_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_doseresponse',
            index=models.Index(fields=['source_id'], name='adr_src_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_doseresponse',
            index=models.Index(fields=['result_type'], name='adr_rty_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_doseresponse',
            index=models.Index(fields=['act_score'], name='adr_act_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_doseresponse',
            index=models.Index(fields=['data_quality'], name='adr_dqc_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_singleconc',
            index=models.Index(fields=['compound_id'], name='asc_cmp_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_singleconc',
            index=models.Index(fields=['assay_id'], name='asc_ass_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_singleconc',
            index=models.Index(fields=['source_id'], name='asc_src_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_singleconc',
            index=models.Index(fields=['result_type'], name='asc_rty_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_singleconc',
            index=models.Index(fields=['act_score'], name='asc_act_idx'),
        ),
        migrations.AddIndex(
            model_name='activity_singleconc',
            index=models.Index(fields=['data_quality'], name='asc_dqc_idx'),
        ),
        migrations.AlterModelTable(
            name='activity_doseresponse',
            table='act_doseresponse',
        ),
        migrations.AlterModelTable(
            name='activity_singleconc',
            table='act_singleconc',
        ),
    ]
